### ISSUE TITLE
Some abilities not refunding rage on miss/dodge/parry

### ISSUE THREAD

**Issue by kaleharbick** [magey/classic-warrior#27]
As shown in these screen shots below, Cleave is costing full rage with dodge/miss/parry.  Magey found this video showing at least Hamstring and Heroic Strike should only cost a fraction on whiffs: https://www.youtube.com/watch?v=ISx6eni6I1k&feature=youtu.be&t=63

I was able to verify that Execute refunds 84%, and Pyte says Shield Slam parry/dodge/miss are refunding, so it appears only some abilities are bugged.

[yellowragecost.zip](https://github.com/magey/classic-warrior/files/3371183/yellowragecost.zip)

**Comment by kaleharbick** [comment]
forum post: https://us.forums.blizzard.com/en/wow/t/bug-some-warrior-abilities-not-refunding-rage-on-miss-dodge-parry/220767

**Comment by magey** [comment]
More tests done by Pyte on the beta show that special abilities refund rage on a whiff except for Whirlwind and Cleave. Upon further examination of the George video, you can see both Whirlwind and Cleave get dodged at [this timestamp](https://youtu.be/ISx6eni6I1k?t=38). Analyzing this segment at 0.5 speed shows that when he uses Whirlwind he goes from 50 to 26 rage (assuming the 1 rage difference is due to all the incoming damage he's receiving there), and then when Cleave goes off he goes from 26 to 6 rage. Both WW and Cleave get dodged there, so it looks like there is no refund for these abilities.

I'm closing this issue and removing the bug tag since it looks like the beta is working correctly.
