### ISSUE TITLE
Incorrect miss chance values in the weapon skill table (?)

### ISSUE THREAD

**Issue by chycharlie** [magey/classic-warrior#34]
If I understand the formulae correctly, the table in the Weapon Skill section should be:

Δ	Glancing    		Miss 	Hit cap
15	35% (~35.12)		8.0%	9.0%
14	31%				7.6%	8.6%
13	27% (~26.74%)	7.2%	8.2%
12	23% (~22.72%)	6.8%	7.8%
11	19%				6.4%	7.4%
10	15% (~14.82%)	6.0%	6.0%

The current table in Wiki has the correct values in the "Hit cap" column (+1% due to some code in 1.12), but the values in the "Miss" column are wrong.

**Comment by Cleavis** [comment]
Hit Suppression due to skill difference is itself a linear function. It is not fixed at 1%.

You can see the relevant formula for Miss between 11 and 15 Δ in the preceding section
```
If the target is a mob and defense minus weapon skill is 11 or more:
    MissChance = 5% + (TargetLevel*5 - AttackerSkill) * 0.2%
    HitSuppression = (TargetLevel*5 - AttackerSkill - 10) * 0.2%
```
Using the formula at Δ=13, for example, MissChance = 5% + ((13)*0.2%) = 7.6%
This value matches the table in the Weapon Skill section.

**Comment by Cleavis** [comment]
If the formula looks incorrect according to empirical testing, feel free to open a ticket with that analysis
